# Generated by Django 5.2.4 on 2025-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='language',
            field=models.CharField(default='zh-CN', max_length=50),
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='Untitled List', max_length=255),
        ),
    ]
